# Generated by Django 4.2.2 on 2023-08-28 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=100, null=True)),
                ("Phone", models.CharField(blank=True, max_length=200, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "end_date",
                    models.DateField(
                        default=datetime.datetime(
                            2023, 9, 7, 13, 18, 59, 196649, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
