# Generated by Django 4.2.2 on 2023-08-30 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="Email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="Message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 9, 9, 19, 57, 11073, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
