# Generated by Django 4.2.2 on 2023-09-09 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0002_contact_email_contact_message_alter_contact_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 19, 15, 2, 24, 933456, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
