# Generated by Django 4.2.2 on 2023-08-28 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0003_deal_delete_task"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="file",
        ),
        migrations.AlterField(
            model_name="deal",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 7, 13, 18, 59, 194649, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
