# Generated by Django 4.2.2 on 2023-08-30 09:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_remove_deal_file_alter_deal_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 9, 9, 19, 57, 10073, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
