# Generated by Django 4.2.2 on 2023-09-09 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_alter_deal_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 19, 15, 2, 24, 932452, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
