# Generated by Django 4.1.3 on 2023-09-09 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0006_alter_deal_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(
                    2023, 9, 19, 15, 4, 58, 323177, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
